"use client";

import { useState } from "react";
import { 
  Building2, 
  MapPin, 
  AlertTriangle, 
  ShieldCheck, 
  ArrowRight, 
  Zap, 
  Sparkles, 
  FileText, 
  Download, 
  Printer, 
  Copy, 
  Check, 
  X,
  Activity,
  CheckCircle2,
  Layers,
  Wrench
} from "lucide-react";
import Link from "next/link";

interface BuildingItem {
  id: string;
  name: string;
  type: string;
  location: string;
  status: "healthy" | "warning" | "critical";
  healthScore: number;
  activeAlerts: number;
  totalAssets: number;
  monitoredAssets: string[];
  energyEfficiency: string;
  estimatedMaintenanceCost?: string;
  nextScheduledAudit?: string;
}

export default function BuildingsPage() {
  const [buildings] = useState<BuildingItem[]>([
    {
      id: "BLD-N01",
      name: "HQ - North Tower",
      type: "Commercial Office",
      location: "Downtown District",
      status: "warning",
      healthScore: 61.0,
      activeAlerts: 1,
      totalAssets: 240,
      monitoredAssets: ["HVAC-01", "ELEVATOR-01"],
      energyEfficiency: "A+",
      estimatedMaintenanceCost: "$4,200",
      nextScheduledAudit: "In 4 days (Oct 13)",
    },
    {
      id: "BLD-W02",
      name: "Tech Hub - West Campus",
      type: "Research Facility",
      location: "Innovation Park",
      status: "warning",
      healthScore: 71.5,
      activeAlerts: 1,
      totalAssets: 240,
      monitoredAssets: ["PUMP-01", "CHILLER-01"],
      energyEfficiency: "B",
      estimatedMaintenanceCost: "$3,800",
      nextScheduledAudit: "In 7 days (Oct 16)",
    },
    {
      id: "BLD-S03",
      name: "Logistics Center - South",
      type: "Warehouse",
      location: "Industrial Zone",
      status: "healthy",
      healthScore: 90.0,
      activeAlerts: 0,
      totalAssets: 120,
      monitoredAssets: ["GENERATOR-01"],
      energyEfficiency: "A",
      estimatedMaintenanceCost: "$950",
      nextScheduledAudit: "In 28 days (Nov 06)",
    },
  ]);

  const [selectedBuildingForReport, setSelectedBuildingForReport] = useState<BuildingItem | null>(null);
  const [showPortfolioReport, setShowPortfolioReport] = useState(false);
  const [copiedReport, setCopiedReport] = useState(false);

  const avgHealth = (buildings.reduce((acc, b) => acc + b.healthScore, 0) / (buildings.length || 1)).toFixed(1);
  const totalAlerts = buildings.reduce((acc, b) => acc + b.activeAlerts, 0);
  const totalAssetsCount = buildings.reduce((acc, b) => acc + b.totalAssets, 0);

  const handleDownloadJSON = (building?: BuildingItem) => {
    const reportData = building ? {
      reportType: "BuildGuard Facility Health & Asset Audit Report",
      buildingId: building.id,
      buildingName: building.name,
      type: building.type,
      location: building.location,
      healthScore: building.healthScore,
      status: building.status,
      activeAlerts: building.activeAlerts,
      monitoredEquipment: building.monitoredAssets,
      energyEfficiency: building.energyEfficiency,
      generatedAt: new Date().toISOString(),
    } : {
      reportType: "BuildGuard Global Portfolio Facilities Audit Report",
      generatedAt: new Date().toISOString(),
      summary: {
        totalFacilities: buildings.length,
        averageHealth: avgHealth,
        totalAlerts,
        totalAssets: totalAssetsCount,
      },
      facilities: buildings,
    };

    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `BuildGuard_${building ? building.id : "Portfolio"}_Audit_Report_${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyMarkdown = (building?: BuildingItem) => {
    let markdown = "";
    if (building) {
      markdown = `# 🏢 BUILDGUARD AI — FACILITY AUDIT REPORT
Building: ${building.name} (${building.id})
Type: ${building.type} | Location: ${building.location}
Date: ${new Date().toLocaleString()}

- **Health Score**: ${building.healthScore}%
- **Operational Status**: ${building.status.toUpperCase()}
- **Active Alerts**: ${building.activeAlerts}
- **Energy Rating**: ${building.energyEfficiency}
- **Monitored Assets**: ${building.monitoredAssets.join(", ")}
- **Estimated Maintenance Cost**: ${building.estimatedMaintenanceCost || "$0"}
- **Next Scheduled Audit**: ${building.nextScheduledAudit || "TBD"}

*Generated by BuildGuard Autonomous Building Intelligence Engine.*`;
    } else {
      markdown = `# 🏢 BUILDGUARD AI — FACILITIES PORTFOLIO AUDIT REPORT
Generated: ${new Date().toLocaleString()}

## Portfolio Summary
- **Total Monitored Facilities**: ${buildings.length}
- **Average Portfolio Health**: ${avgHealth}%
- **Active Alerts Across Portfolio**: ${totalAlerts}
- **Total Physical Assets**: ${totalAssetsCount}

## Monitored Buildings Breakdown
${buildings.map(b => `### ${b.name} (${b.id})
- Type: ${b.type} · Location: ${b.location}
- Health Score: ${b.healthScore}% · Status: ${b.status.toUpperCase()}
- Active Alerts: ${b.activeAlerts} · Efficiency: ${b.energyEfficiency}
- Equipment: ${b.monitoredAssets.join(", ")}
`).join("\n")}
*Report certified by BuildGuard Multi-Agent Neuro-Symbolic AI Engine.*`;
    }

    navigator.clipboard.writeText(markdown);
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2500);
  };

  return (
    <div className="flex flex-col gap-6 sm:gap-8 pb-16">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-semibold tracking-tight text-white flex items-center gap-2.5">
            <span>Facilities Portfolio Health</span>
            <span className="text-xs font-mono font-normal px-2.5 py-0.5 rounded-full bg-primary/10 text-primary border border-primary/20">
              Multi-Facility
            </span>
          </h1>
          <p className="text-foreground/60 text-xs sm:text-sm mt-1">
            Real-time multi-agent health aggregation and comprehensive building maintenance audit reports.
          </p>
        </div>
        
        <div className="flex items-center gap-2.5 flex-wrap">
          <button
            onClick={() => setShowPortfolioReport(true)}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-primary text-black font-semibold text-xs sm:text-sm hover:bg-primary/90 transition-all shadow-md active:scale-95 cursor-pointer"
          >
            <FileText className="w-4 h-4" />
            <span>Generate Portfolio Report</span>
          </button>
        </div>
      </div>

      {/* Summary KPI row */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-6">
        <div className="glass-panel p-4 sm:p-5 rounded-2xl border border-white/5 flex flex-col gap-1">
          <div className="text-[11px] text-foreground/50 font-mono uppercase">Monitored Facilities</div>
          <div className="text-2xl sm:text-3xl font-bold font-mono text-white">{buildings.length}</div>
        </div>
        <div className="glass-panel p-4 sm:p-5 rounded-2xl border border-white/5 flex flex-col gap-1">
          <div className="text-[11px] text-foreground/50 font-mono uppercase">Average Portfolio Health</div>
          <div className="text-2xl sm:text-3xl font-bold font-mono text-[#4ade80]">{avgHealth}%</div>
        </div>
        <div className="glass-panel p-4 sm:p-5 rounded-2xl border border-white/5 flex flex-col gap-1">
          <div className="text-[11px] text-foreground/50 font-mono uppercase">Active Equipment Alerts</div>
          <div className={`text-2xl sm:text-3xl font-bold font-mono ${totalAlerts > 0 ? "text-warning" : "text-[#4ade80]"}`}>
            {totalAlerts}
          </div>
        </div>
      </div>

      {/* Facility Cards */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-4 sm:gap-6">
        {buildings.map((b) => (
          <div
            key={b.id}
            className="glass-panel p-5 sm:p-6 rounded-2xl border border-white/5 flex flex-col gap-4 hover:border-primary/40 transition-all group relative overflow-hidden shadow-lg"
          >
            <div
              className="absolute top-0 left-0 w-full h-1"
              style={{ backgroundColor: b.status === "healthy" ? "#10b981" : b.status === "warning" ? "#f59e0b" : "#ef4444" }}
            />

            <div className="flex flex-col xs:flex-row justify-between items-start gap-3">
              <div className="flex gap-3.5 items-start">
                <div className="p-2.5 sm:p-3 bg-panel border border-panel-border rounded-xl shrink-0">
                  <Building2 className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <h2 className="text-base sm:text-lg font-semibold tracking-tight text-white group-hover:text-primary transition-colors">
                    {b.name}
                  </h2>
                  <div className="flex gap-2 text-xs text-foreground/60 flex-wrap mt-0.5">
                    <span className="font-mono">{b.id}</span>
                    <span>•</span>
                    <span className="flex items-center gap-1">
                      <MapPin className="w-3 h-3" /> {b.location}
                    </span>
                  </div>
                </div>
              </div>

              <div
                className={`px-2.5 py-1 rounded-md text-xs font-mono font-medium flex items-center gap-1.5 self-start ${
                  b.status === "healthy"
                    ? "bg-[#4ade80]/10 text-[#4ade80] border border-[#4ade80]/20"
                    : b.status === "warning"
                    ? "bg-warning/10 text-warning border border-warning/20"
                    : "bg-critical/10 text-critical border border-critical/20"
                }`}
              >
                {b.status === "healthy" ? <ShieldCheck className="w-3.5 h-3.5" /> : <AlertTriangle className="w-3.5 h-3.5 text-warning" />}
                {b.status.toUpperCase()}
              </div>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-white/[0.02] p-3 rounded-xl border border-white/5">
              <div className="flex flex-col gap-0.5">
                <span className="text-[10px] text-foreground/50 font-mono uppercase">Health Score</span>
                <span className="text-base font-semibold font-mono text-white">{b.healthScore}%</span>
              </div>
              <div className="flex flex-col gap-0.5">
                <span className="text-[10px] text-foreground/50 font-mono uppercase">Alerts</span>
                <span className={`text-base font-semibold font-mono ${b.activeAlerts > 0 ? "text-warning" : "text-[#4ade80]"}`}>
                  {b.activeAlerts}
                </span>
              </div>
              <div className="flex flex-col gap-0.5">
                <span className="text-[10px] text-foreground/50 font-mono uppercase">Total Assets</span>
                <span className="text-base font-semibold font-mono text-white">{b.totalAssets}</span>
              </div>
              <div className="flex flex-col gap-0.5">
                <span className="text-[10px] text-foreground/50 font-mono uppercase">Efficiency</span>
                <span className="text-base font-semibold flex items-center gap-1 font-mono text-primary">
                  <Zap className="w-3.5 h-3.5" /> {b.energyEfficiency}
                </span>
              </div>
            </div>

            <div className="flex flex-col xs:flex-row justify-between items-start xs:items-center gap-2 pt-2 border-t border-panel-border/40">
              <span className="text-[11px] text-foreground/60 font-mono">
                Equipment: {b.monitoredAssets.join(", ")}
              </span>
              
              <div className="flex items-center gap-3 self-end xs:self-auto">
                <button
                  onClick={() => setSelectedBuildingForReport(b)}
                  className="text-xs font-semibold text-primary/90 hover:text-primary flex items-center gap-1 hover:underline cursor-pointer"
                >
                  <FileText className="w-3.5 h-3.5" />
                  <span>Generate Report</span>
                </button>
                <Link href="/overview" className="text-xs font-semibold text-primary flex items-center gap-1 hover:underline">
                  <span>Telemetry</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* INDIVIDUAL BUILDING REPORT MODAL */}
      {selectedBuildingForReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-white text-slate-900 border border-slate-300 rounded-3xl w-full max-w-3xl max-h-[92vh] overflow-y-auto p-6 sm:p-10 flex flex-col gap-6 shadow-2xl custom-scrollbar relative font-sans">
            <button
              onClick={() => setSelectedBuildingForReport(null)}
              className="absolute top-5 right-5 p-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors no-print cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>

            {/* Document Header */}
            <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 pb-6 border-b-2 border-slate-900">
              <div className="flex items-start gap-3.5">
                <div className="w-12 h-12 rounded-xl bg-slate-900 text-cyan-400 flex items-center justify-center font-mono font-bold text-xl shrink-0 shadow-md">
                  BG
                </div>
                <div>
                  <div className="text-[11px] font-mono uppercase tracking-widest text-slate-500 font-bold">
                    BUILDGUARD INFRASTRUCTURE SYSTEMS · FACILITY AUDIT DIVISION
                  </div>
                  <h2 className="text-xl sm:text-2xl font-black text-slate-950 tracking-tight mt-0.5">
                    FACILITY HEALTH & MAINTENANCE AUDIT REPORT
                  </h2>
                  <p className="text-xs text-slate-600 font-medium mt-0.5">
                    {selectedBuildingForReport.type} · {selectedBuildingForReport.location}
                  </p>
                </div>
              </div>

              <div className="bg-slate-100 p-2.5 rounded-xl border border-slate-300 font-mono text-xs text-right shrink-0">
                <div><strong>DOC ID:</strong> BG-FAC-{selectedBuildingForReport.id}</div>
                <div><strong>DATE:</strong> {new Date().toLocaleDateString()}</div>
                <div><strong>STANDARD:</strong> ISO 55000 Asset Mgmt</div>
              </div>
            </div>

            {/* Executive Summary Rating */}
            <div className={`p-4 sm:p-5 rounded-2xl border flex items-center justify-between gap-4 ${
              selectedBuildingForReport.status === "healthy"
                ? "bg-emerald-50 border-emerald-300 text-emerald-950"
                : selectedBuildingForReport.status === "warning"
                ? "bg-amber-50 border-amber-300 text-amber-950"
                : "bg-rose-50 border-rose-300 text-rose-950"
            }`}>
              <div className="flex items-center gap-4">
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center font-bold text-lg text-white shrink-0 ${
                  selectedBuildingForReport.status === "healthy"
                    ? "bg-emerald-600"
                    : selectedBuildingForReport.status === "warning"
                    ? "bg-amber-600"
                    : "bg-rose-600"
                }`}>
                  {selectedBuildingForReport.healthScore}%
                </div>
                <div>
                  <div className="text-[10px] font-mono uppercase font-bold opacity-70">
                    FACILITY OPERATIONAL INTEGRITY SCORE
                  </div>
                  <div className="text-lg sm:text-xl font-black tracking-tight">
                    STATUS: {selectedBuildingForReport.status.toUpperCase()} ({selectedBuildingForReport.status === "healthy" ? "NOMINAL" : "ACTION REQUIRED"})
                  </div>
                </div>
              </div>

              <div className="text-right font-mono text-xs font-bold shrink-0">
                <div>Energy Rating: {selectedBuildingForReport.energyEfficiency}</div>
                <div>Active Alerts: {selectedBuildingForReport.activeAlerts}</div>
              </div>
            </div>

            {/* Metrics Breakdown Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 p-4 rounded-xl border border-slate-200 text-xs">
              <div className="flex flex-col">
                <span className="text-[10px] uppercase font-mono text-slate-500 font-semibold">Total Physical Assets</span>
                <span className="text-lg font-bold font-mono text-slate-900 mt-0.5">{selectedBuildingForReport.totalAssets} Units</span>
              </div>
              <div className="flex flex-col">
                <span className="text-[10px] uppercase font-mono text-slate-500 font-semibold">Critical Monitored Equipment</span>
                <span className="text-lg font-bold font-mono text-slate-900 mt-0.5">{selectedBuildingForReport.monitoredAssets.length} Assets</span>
              </div>
              <div className="flex flex-col">
                <span className="text-[10px] uppercase font-mono text-slate-500 font-semibold">Est. Maintenance Reserve</span>
                <span className="text-lg font-bold font-mono text-slate-900 mt-0.5">{selectedBuildingForReport.estimatedMaintenanceCost || "$0"}</span>
              </div>
              <div className="flex flex-col">
                <span className="text-[10px] uppercase font-mono text-slate-500 font-semibold">Next Scheduled Audit</span>
                <span className="text-sm font-bold font-mono text-cyan-700 mt-0.5">{selectedBuildingForReport.nextScheduledAudit || "Routine"}</span>
              </div>
            </div>

            {/* Connected Critical Equipment Status Table */}
            <div className="flex flex-col gap-2">
              <span className="text-xs font-mono font-bold uppercase text-slate-700">Monitored Critical Equipment Condition</span>
              <div className="border border-slate-300 rounded-xl overflow-hidden shadow-sm">
                <table className="w-full text-xs text-left">
                  <thead className="bg-slate-100 text-slate-700 font-mono border-b border-slate-300">
                    <tr>
                      <th className="p-3">Asset Designation</th>
                      <th className="p-3">Telemetry Stream</th>
                      <th className="p-3">Predictive RUL</th>
                      <th className="p-3 text-right">Integrity Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200 font-medium">
                    {selectedBuildingForReport.monitoredAssets.map((asset) => (
                      <tr key={asset} className="hover:bg-slate-50">
                        <td className="p-3 font-semibold text-slate-900">{asset}</td>
                        <td className="p-3 text-slate-600 font-mono">Continuous Multi-Agent IoT</td>
                        <td className="p-3 font-mono font-bold text-slate-800">
                          {asset.includes("PUMP") ? "6.2 Days" : asset.includes("HVAC") ? "12.4 Days" : "78.0 Days"}
                        </td>
                        <td className="p-3 text-right">
                          <span className="inline-flex items-center gap-1 font-mono text-[11px] font-bold text-emerald-700 bg-emerald-100 px-2 py-0.5 rounded">
                            <CheckCircle2 className="w-3 h-3" /> VERIFIED
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Engineering Sign-Off Box */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-4 border-t-2 border-slate-300 text-xs">
              <div className="flex flex-col gap-0.5">
                <span className="text-[10px] font-mono uppercase text-slate-500 font-bold">Facility Auditor</span>
                <div className="font-mono text-slate-900 font-semibold border-b border-slate-300 pb-1">J. Martinez, CEM, CEA</div>
                <span className="text-[10px] text-slate-500 font-mono">Certified Energy & Facility Manager</span>
              </div>
              <div className="flex flex-col gap-0.5">
                <span className="text-[10px] font-mono uppercase text-slate-500 font-bold">System Validation Hash</span>
                <div className="font-mono text-slate-800 text-[10px] border-b border-slate-300 pb-1 break-all">SHA-256: 4C8A99F12B...</div>
                <span className="text-[10px] text-slate-500 font-mono">BuildGuard AI Node Certified</span>
              </div>
              <div className="flex flex-col gap-0.5 text-right">
                <span className="text-[10px] font-mono uppercase text-slate-500 font-bold">Audit Classification</span>
                <div className="font-mono text-slate-900 font-bold border-b border-slate-300 pb-1">LEVEL 2 COMPREHENSIVE</div>
                <span className="text-[10px] text-emerald-700 font-mono font-bold">✓ AUDIT SIGNED</span>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex items-center justify-between gap-3 pt-4 border-t border-slate-200 flex-wrap no-print">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleCopyMarkdown(selectedBuildingForReport)}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-medium border border-slate-300 transition-all cursor-pointer"
                >
                  {copiedReport ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedReport ? "Copied!" : "Copy Markdown"}</span>
                </button>
                <button
                  onClick={() => handleDownloadJSON(selectedBuildingForReport)}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-medium border border-slate-300 transition-all cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5 text-cyan-700" />
                  <span>Export JSON</span>
                </button>
              </div>

              <button
                onClick={() => window.print()}
                className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-slate-900 text-white font-bold text-xs hover:bg-slate-800 transition-all shadow-lg cursor-pointer"
              >
                <Printer className="w-4 h-4 text-cyan-400" />
                <span>Print Official PDF Report</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* PORTFOLIO REPORT MODAL */}
      {showPortfolioReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-white text-slate-900 border border-slate-300 rounded-3xl w-full max-w-4xl max-h-[92vh] overflow-y-auto p-6 sm:p-10 flex flex-col gap-6 shadow-2xl custom-scrollbar relative font-sans">
            <button
              onClick={() => setShowPortfolioReport(false)}
              className="absolute top-5 right-5 p-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors no-print cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>

            {/* Modal Header */}
            <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 pb-6 border-b-2 border-slate-900">
              <div className="flex items-start gap-3.5">
                <div className="w-12 h-12 rounded-xl bg-slate-900 text-cyan-400 flex items-center justify-center font-mono font-bold text-xl shrink-0 shadow-md">
                  BG
                </div>
                <div>
                  <div className="text-[11px] font-mono uppercase tracking-widest text-slate-500 font-bold">
                    BUILDGUARD AI INFRASTRUCTURE SYSTEMS · PORTFOLIO MANAGEMENT
                  </div>
                  <h2 className="text-xl sm:text-2xl font-black text-slate-950 tracking-tight mt-0.5">
                    GLOBAL REAL ESTATE & FACILITIES PORTFOLIO AUDIT
                  </h2>
                  <p className="text-xs text-slate-600 font-medium mt-0.5">
                    Aggregate multi-agent telemetry analysis across {buildings.length} monitored commercial facilities
                  </p>
                </div>
              </div>

              <div className="bg-slate-100 p-2.5 rounded-xl border border-slate-300 font-mono text-xs text-right shrink-0">
                <div><strong>DOC REF:</strong> BG-PORTFOLIO-{(new Date().getFullYear())}</div>
                <div><strong>DATE:</strong> {new Date().toLocaleDateString()}</div>
                <div><strong>STANDARD:</strong> ISO 55000 / BREEAM</div>
              </div>
            </div>

            {/* KPI Summary */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 p-4 rounded-xl border border-slate-200">
              <div className="flex flex-col">
                <span className="text-[10px] uppercase font-mono text-slate-500 font-semibold">Average Portfolio Health</span>
                <span className="text-2xl font-bold font-mono text-emerald-600 mt-1">{avgHealth}%</span>
              </div>
              <div className="flex flex-col">
                <span className="text-[10px] uppercase font-mono text-slate-500 font-semibold">Monitored Facilities</span>
                <span className="text-2xl font-bold font-mono text-slate-900 mt-1">{buildings.length}</span>
              </div>
              <div className="flex flex-col">
                <span className="text-[10px] uppercase font-mono text-slate-500 font-semibold">Total Physical Assets</span>
                <span className="text-2xl font-bold font-mono text-slate-900 mt-1">{totalAssetsCount}</span>
              </div>
              <div className="flex flex-col">
                <span className="text-[10px] uppercase font-mono text-slate-500 font-semibold">Active Equipment Alerts</span>
                <span className={`text-2xl font-bold font-mono mt-1 ${totalAlerts > 0 ? "text-amber-600" : "text-emerald-600"}`}>{totalAlerts}</span>
              </div>
            </div>

            {/* Breakdown Table */}
            <div className="flex flex-col gap-2">
              <span className="text-xs font-mono font-bold uppercase text-slate-700">Facilities Breakdown Matrix</span>
              <div className="border border-slate-300 rounded-xl overflow-hidden shadow-sm">
                <table className="w-full text-xs text-left">
                  <thead className="bg-slate-100 text-slate-700 font-mono border-b border-slate-300">
                    <tr>
                      <th className="p-3">Facility Name</th>
                      <th className="p-3">Sector Location</th>
                      <th className="p-3">Health Score</th>
                      <th className="p-3">Active Alerts</th>
                      <th className="p-3">Efficiency</th>
                      <th className="p-3 text-right">Maintenance Reserve</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200 font-medium">
                    {buildings.map(b => (
                      <tr key={b.id} className="hover:bg-slate-50">
                        <td className="p-3 font-semibold text-slate-900">{b.name}</td>
                        <td className="p-3 text-slate-600">{b.location}</td>
                        <td className="p-3 font-mono font-bold text-emerald-700">{b.healthScore}%</td>
                        <td className="p-3 font-mono">
                          {b.activeAlerts > 0 ? (
                            <span className="text-amber-700 font-bold bg-amber-100 px-2 py-0.5 rounded">{b.activeAlerts} Warning</span>
                          ) : (
                            <span className="text-emerald-700 bg-emerald-100 px-2 py-0.5 rounded">0 Nominal</span>
                          )}
                        </td>
                        <td className="p-3 font-mono font-bold text-cyan-700">{b.energyEfficiency}</td>
                        <td className="p-3 text-right font-mono font-bold text-slate-900">{b.estimatedMaintenanceCost || "$0"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Actions */}
            <div className="flex items-center justify-between gap-3 pt-4 border-t border-slate-200 flex-wrap no-print">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleCopyMarkdown()}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-medium border border-slate-300 transition-all cursor-pointer"
                >
                  {copiedReport ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedReport ? "Copied!" : "Copy Markdown"}</span>
                </button>
                <button
                  onClick={() => handleDownloadJSON()}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-medium border border-slate-300 transition-all cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5 text-cyan-700" />
                  <span>Export JSON</span>
                </button>
              </div>

              <button
                onClick={() => window.print()}
                className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-slate-900 text-white font-bold text-xs hover:bg-slate-800 transition-all shadow-lg cursor-pointer"
              >
                <Printer className="w-4 h-4 text-cyan-400" />
                <span>Print Official PDF Report</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

